# Generated by Django 5.1.1 on 2024-10-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_pesel_alter_patient_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
