# Generated by Django 5.1.1 on 2024-10-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_images_examination_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
